spring.application.name=pr-guardian-lite

spring.data.mongodb.uri=mongodb://localhost:27017/pr_guardian

server.port=8080

# OpenRouter API
openrouter.api-key=${OPENROUTER_API_KEY:}

# Free OpenRouter LLM route
llm.model=openrouter/free

# Free OpenRouter embedding model
embedding.model=nvidia/nemotron-3-embed-1b:free